#!/usr/bin/env python3
"""Turn a study's result files into the macros and table the paper includes.

Every number in the paper comes from here, so none of them is typed by hand.

    python studies/make_paper_numbers.py --model hf:Qwen/Qwen3-0.6B
"""

from __future__ import annotations

import argparse
import json
import sys
from math import comb
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.dminds import paths  # noqa: E402

ORDER = ["intact", "rewritten", "erased"]
SHOWN = {
    "intact": r"\textsc{intact}",
    "rewritten": r"\textsc{rewritten}",
    "erased": r"\textsc{erased}",
}


def pct(part: int, whole: int) -> str:
    return f"{100.0 * part / whole:.0f}" if whole else "0"


def fisher_one_sided(a: int, b: int, c: int, d: int) -> float:
    """P(table this extreme or more) for the 2x2 table [[a,b],[c,d]].

    Rows are conditions and columns are hit and miss. One-sided, testing that
    the first row has more hits, which is the direction the experiment plants.
    """
    row1, row2 = a + b, c + d
    col1 = a + c
    total = row1 + row2
    p = 0.0
    for k in range(a, min(row1, col1) + 1):
        p += comb(row1, k) * comb(row2, col1 - k) / comb(total, col1)
    return p


def mcnemar_exact(b: int, c: int) -> float:
    """Two-sided exact test on the discordant pairs of a paired comparison."""
    n = b + c
    if n == 0:
        return 1.0
    k = min(b, c)
    tail = sum(comb(n, i) for i in range(k + 1)) / 2**n
    return min(1.0, 2 * tail)


def fmt_p(p: float) -> str:
    """A p-value as LaTeX, with a floor rather than a misleading zero."""
    if p < 1e-4:
        return r"$p < 10^{-4}$"
    return rf"$p = {p:.3f}$"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="hf:Qwen/Qwen3-0.6B")
    parser.add_argument("--out", default=str(ROOT / "paper" / "sections"))
    args = parser.parse_args()

    slug = args.model.replace(":", "-").replace("/", "-")
    folder = paths.OUT / "studies" / "introspection" / slug
    rows = json.loads((folder / "results.json").read_text())
    modes = [m for m in ORDER if any(r["mode"] == m for r in rows)]

    stats = {}
    for mode in modes:
        subset = [r for r in rows if r["mode"] == mode]
        stats[mode] = {
            "n": len(subset),
            "obeys": sum(r["answer_obeys"] for r in subset),
            "claims": sum(r["report_claims_marker"] for r in subset),
            "reports": sum(not r["report_is_empty"] for r in subset),
        }

    # Does planting move obedience above the base rate, and does the report
    # follow the answer? The first is between conditions, the second is a
    # paired comparison inside the planted condition.
    planted = [r for r in rows if r["mode"] == "rewritten"]
    base = [r for r in rows if r["mode"] in ("intact", "erased")]
    p_obey = fisher_one_sided(
        sum(r["answer_obeys"] for r in planted),
        sum(not r["answer_obeys"] for r in planted),
        sum(r["answer_obeys"] for r in base),
        sum(not r["answer_obeys"] for r in base),
    )
    only_obeys = sum(
        r["answer_obeys"] and not r["report_claims_marker"] for r in planted
    )
    only_claims = sum(
        r["report_claims_marker"] and not r["answer_obeys"] for r in planted
    )
    p_gap = mcnemar_exact(only_obeys, only_claims)
    delivered = sum(r["ego_saw_marker"] for r in planted)

    out = Path(args.out)
    macros = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        rf"\newcommand{{\probeModel}}{{\texttt{{{args.model.split(':', 1)[1]}}}}}",
        rf"\newcommand{{\probeQuestions}}{{{stats[modes[0]]['n']}}}",
        rf"\newcommand{{\probeTrials}}{{{len(rows)}}}",
        rf"\newcommand{{\probeConditions}}{{{len(modes)}}}",
        rf"\newcommand{{\pObey}}{{{fmt_p(p_obey)}}}",
        rf"\newcommand{{\pGap}}{{{fmt_p(p_gap)}}}",
        rf"\newcommand{{\probeDelivered}}{{{delivered}}}",
    ]
    for mode in modes:
        s = stats[mode]
        tag = mode.capitalize()
        macros += [
            rf"\newcommand{{\obeys{tag}}}{{{s['obeys']}}}",
            rf"\newcommand{{\obeys{tag}Pct}}{{{pct(s['obeys'], s['n'])}}}",
            rf"\newcommand{{\claims{tag}}}{{{s['claims']}}}",
            rf"\newcommand{{\claims{tag}Pct}}{{{pct(s['claims'], s['n'])}}}",
            rf"\newcommand{{\reports{tag}}}{{{s['reports']}}}",
        ]
    (out / "generated_numbers.tex").write_text("\n".join(macros) + "\n")

    lines = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{What a planted thought does to an answer, and what the mind",
        r"then says about its own reasoning. Each row is the same "
        + str(stats[modes[0]]["n"])
        + r" questions",
        r"under one condition, run on \probeModel. \emph{Obeys} counts answers",
        r"containing the planted marker. \emph{Claims it} counts self-reports",
        r"that name the planted commitment as the mind's own reasoning.",
        r"\textsc{intact} and \textsc{erased} carry no planted thought and give",
        rf"the base rate. The planted commitment reached the ego in {delivered} of"
        rf" the {len(planted)}",
        r"planted trials, because in the rest the subject produced no reasoning to",
        r"replace. Planting moves obedience above that base rate",
        "(" + fmt_p(p_obey) + r", one-sided Fisher exact), and inside the",
        r"planted condition the answer follows the thought more often than the",
        r"report names it (" + fmt_p(p_gap) + r", exact McNemar).}",
        r"\label{tab:probe}",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"condition & planted & $n$ & obeys & claims it \\",
        r"\midrule",
    ]
    for mode in modes:
        s = stats[mode]
        has_plant = "yes" if mode == "rewritten" else "no"
        lines.append(
            f"{SHOWN[mode]} & {has_plant} & {s['n']} & "
            f"{s['obeys']} ({pct(s['obeys'], s['n'])}\\%) & "
            f"{s['claims']} ({pct(s['claims'], s['n'])}\\%) \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    (out / "table_probe.tex").write_text("\n".join(lines) + "\n")

    print(f"  read   {folder}/results.json  ({len(rows)} trials)")
    for mode in modes:
        s = stats[mode]
        print(
            f"  {mode:<10} n={s['n']:<3} obeys={s['obeys']:<3} "
            f"claims={s['claims']:<3} reported={s['reports']}"
        )
    print(f"  wrote  {out}/generated_numbers.tex and table_probe.tex")


if __name__ == "__main__":
    main()
