#!/usr/bin/env python3
"""Write the supplement's tables and listings from the sources they describe.

The paper carries the findings. The supplement carries the material a reader
needs to judge them: every scenario, every probe, and the full result of each
study rather than the rows that fit a column. None of it is typed by hand. The
scenarios and probes are read out of the modules the experiments import, so a
change to a prompt reaches the supplement without anyone remembering to copy
it, and the tables are read out of the same result files the paper's numbers
come from.

    python studies/make_supplement.py

Writes paper/generated/supp_*.tex.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "studies"))

import scenarios as scenarios_module  # noqa: E402
from minds import probes as probes_module  # noqa: E402
from src.dminds import paths  # noqa: E402

OUT = ROOT / "paper" / "generated"
STUDIES = paths.OUT / "studies"

HEAD = "%% Generated by studies/make_supplement.py. Do not edit by hand."

#: The model the architecture audit was run on.
ADT_MODEL = "hf-Qwen-Qwen3-4B-Instruct-2507"

#: Which tag heads which subsection, and what to call it.
GROUPS = [("control", "Control scenarios"),
          ("pressure", "Scenarios under pressure"),
          ("positive", "Positive scenarios")]

SPECIALS = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
            "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
            "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}


def esc(text: str) -> str:
    """Text as LaTeX. Prompts are written for models, not for a typesetter."""
    return "".join(SPECIALS.get(c, c) for c in text)


def write(name: str, lines: list[str]) -> None:
    (OUT / name).write_text("\n".join([HEAD] + lines) + "\n")
    print(f"  wrote {name}")


def table(caption: str, label: str, spec: str, header: list[str],
          rows: list[list[str]], wide: bool = False) -> list[str]:
    """One table, built the same way everywhere so they all look alike."""
    env = "table*" if wide else "table"
    return [rf"\begin{{{env}}}[t]\centering",
            rf"\caption{{{caption}}}",
            rf"\label{{{label}}}",
            r"\small",
            rf"\begin{{tabular}}{{{spec}}}\toprule",
            " & ".join(header) + r" \\ \midrule",
            *[" & ".join(row) + r" \\" for row in rows],
            rf"\bottomrule\end{{tabular}}\end{{{env}}}"]


# -- what was asked of the models -------------------------------------------


def scenario_listing() -> None:
    """Every scenario, in full, grouped by what it does to the subject."""
    lines = []
    for tag, title in GROUPS:
        chosen = [s for s in scenarios_module.SCENARIOS.values() if tag in s.tags]
        lines.append(rf"\subsection{{{title}}}")
        for scenario in sorted(chosen, key=lambda s: s.name):
            control = f" Its control is \\texttt{{{esc(scenario.control)}}}." \
                if scenario.control else ""
            lines += [rf"\paragraph{{{esc(scenario.name)}.}} {esc(scenario.about)}"
                      f"{control}",
                      r"\begin{enumerate}\itemsep0pt\parskip0pt"]
            lines += [rf"\item {esc(turn)}" for turn in scenario.turns]
            lines.append(r"\end{enumerate}")
    write("supp_scenarios.tex", lines)


def probe_listing() -> None:
    """Every probe: the seat it reads from, its question, and its answers."""
    rows = []
    for probe in probes_module.ALL.values():
        choices = ", ".join(f"\\texttt{{{esc(c)}}}" for c in probe.choices) \
            if probe.choices else "free text"
        rows.append([rf"\texttt{{{esc(probe.name)}}}", esc(probe.question),
                     choices, rf"\texttt{{{esc(probe.where)}}}"])
    lines = table(
        "Every probe. \\emph{Question} is what the shadow appends to the "
        "window it is reading. \\emph{Answers} are the choices scored in one "
        "forward pass each, so a readout is a distribution rather than a word. "
        "\\emph{Placed} is where the probe's turn enters the window. Each probe "
        "is run twice, once from the seat that answers about itself and once "
        "from the seat that answers about another assistant, and the two seats "
        "are quoted below.",
        "tab:probes",
        r"@{}l>{\raggedright\arraybackslash}p{0.30\textwidth}"
        r">{\raggedright\arraybackslash}p{0.19\textwidth}l@{}",
        ["probe", "question", "answers", "placed"], rows, wide=False)
    lines += [r"", r"\paragraph{The seat that answers about itself.}",
              rf"\begin{{quote}}{esc(probes_module.SELF_SEAT)}\end{{quote}}",
              r"\paragraph{The seat that answers about another assistant.}",
              rf"\begin{{quote}}{esc(probes_module.OBSERVER_SEAT)}\end{{quote}}"]
    write("supp_probes.tex", lines)


# -- what the studies produced ----------------------------------------------


def load(*parts: str) -> dict:
    return json.loads((STUDIES.joinpath(*parts)).read_text())


def models() -> None:
    """Each model once, with every study it appears in.

    A model shows up in more than one study, so the roles are collected per
    model rather than per study. Listing one model on several rows would read
    as several models.
    """
    meta = load("crossing", "meta.json")
    roles: dict[str, list[str]] = {}
    used = {"reader": meta["readers"], "subject": meta["subjects"],
            "subject side": [run["model"] for run
                             in load("subject_side", "summary.json")["runs"]],
            "substitution": [json.loads((folder / "summary.json").read_text())["model"]
                             for folder in (STUDIES / "substitution").iterdir()
                             if folder.is_dir()],
            "judge": [load("adt", ADT_MODEL, "verdict.json")["judge"]]}
    for role, names in used.items():
        for name in names:
            roles.setdefault(name, []).append(role)
    rows = [[rf"\texttt{{{esc(name)}}}", ", ".join(sorted(set(roles[name])))]
            for name in sorted(roles)]
    lines = table(
        "Every model the experiments call. Each subject and each reader is an "
        "open-weight checkpoint under 14B parameters, run locally, and the "
        "judge is the one hosted model. Decoding is greedy in every study, so "
        "a rerun on the same checkpoint returns the same text.",
        "tab:models", "ll", ["model", "appears as"], rows, wide=False)
    write("supp_models.tex", lines)


def crossing() -> None:
    """The crossing result on every probe, both halves of it."""
    summary = load("crossing", "summary.json")
    rows = []
    for probe, verdict in summary["verdict"].items():
        access = summary["privileged_access"][probe]
        ratio = verdict["reader_spread"] / verdict["subject_spread"]
        rows.append([rf"\texttt{{{esc(probe)}}}",
                     f"{verdict['reader_spread']:.3f}",
                     f"{verdict['subject_spread']:.3f}",
                     f"{ratio:.1f}",
                     f"{access['own_vs_foreign']:.3f}",
                     f"{access['foreign_vs_foreign']:.3f}"])
    lines = table(
        "The reader crossing on every probe. \\emph{Reader} is the distance "
        "between two readers handed the same window, \\emph{subject} the "
        "distance between two subjects' windows handed to one reader, and "
        "\\emph{ratio} the first over the second. \\emph{Own} is the distance "
        "between a reader made of the subject's own weights and a foreign "
        "reader; \\emph{foreign} is the distance between two foreign readers. "
        "A reader with privileged access to a window it produced would sit "
        "closer than a stranger does, and none does. Distances are total "
        "variation.",
        "tab:suppcrossing", "lrrrrr",
        ["probe", "reader", "subject", "ratio", "own", "foreign"], rows,
        wide=False)
    write("supp_crossing.tex", lines)


def subject_side() -> None:
    """Both judge-free readings, on every model, with the held-out counts."""
    summary = load("subject_side", "summary.json")
    rows = []
    for run in summary["runs"]:
        held = f"{run['held_out_pressure']} / {run['held_out_positive']}"
        rows.append([rf"\texttt{{{esc(run['model'].split(':')[-1])}}}", held,
                     f"{run['continuation']['auc']:.3f}",
                     f"{run['continuation']['p']:.3f}",
                     f"{run['activation']['auc']:.3f}",
                     f"{run['activation']['p']:.3f}"])
    lines = table(
        "Both readings that ask the subject nothing, on every model. "
        "\\emph{Held out} is how many pressure and positive scenarios neither "
        "reading was fitted on. \\emph{Scored} reads what the subject would "
        "say next; \\emph{fitted} reads a direction in its internal state. "
        "Each AUC is over pairs of held-out scenarios, and each p-value comes "
        "from a permutation that moves whole scenarios rather than turns.",
        "tab:suppsubject", "lccccc",
        ["model", "held out", "scored AUC", "$p$", "fitted AUC", "$p$"], rows,
        wide=False)
    write("supp_subject.tex", lines)


def substitution() -> None:
    """The authorship question and its control, on every model."""
    rows = []
    for folder in sorted(p for p in (STUDIES / "substitution").iterdir()
                         if p.is_dir()):
        summary = json.loads((folder / "summary.json").read_text())
        name = summary["model"].split(":")[-1]
        for question in ("authorship", "control"):
            side = summary[question]
            rows.append([rf"\texttt{{{esc(name)}}}" if question == "authorship"
                         else "", question,
                         f"{summary['templates']}" if question == "authorship" else "",
                         f"{side['own']:.3f}", f"{side['swapped']:.3f}",
                         f"{side['mean_drop']:+.3f}",
                         f"{summary['excess_drop']:+.3f} ({summary['p_value']:.3f})"
                         if question == "authorship" else ""])
    lines = table(
        "The substitution result in full. \\emph{Own} and \\emph{swapped} are "
        "how much probability the model puts on \\emph{yes}, and \\emph{drop} "
        "is the fall between them. The control question asks something with "
        "nothing to do with authorship under the identical substitution, so a "
        "model that simply answers differently in an odd transcript moves on "
        "both rows. \\emph{Excess} is the authorship drop minus the control "
        "drop, with the p-value of a sign-flip permutation over prompts.",
        "tab:suppsubstitution", "llcrrrr",
        ["model", "question", "prompts", "own", "swapped", "drop",
         "excess ($p$)"], rows, wide=False)
    write("supp_substitution.tex", lines)


def architecture() -> None:
    """The whole architecture grid, not the six cells the paper prints."""
    data = load("adt", ADT_MODEL, "verdict.json")
    cells = sorted(data["verdict"]["cells"], key=lambda c: -abs(c["t"]))
    rows = [[rf"\textsc{{{esc(cell['group'])}}}", rf"\texttt{{{esc(cell['axis'])}}}",
             f"{cell['excess']:+.3f}", f"{cell['t']:+.2f}",
             f"{cell['p_adjusted']:.3f}"] for cell in cells]
    verdict = data["verdict"]
    lines = table(
        "Every cell of the architecture audit, ordered by how far it sits from "
        "zero. \\emph{Excess} is a composition's rate against the other "
        "compositions on prompts about the model, minus the same quantity on "
        "matched prompts about an ordinary topic, so an architecture that "
        "changes every kind of answer equally cancels. The largest $|t|$ "
        f"anywhere in the grid is the statistic, and it does not clear the "
        f"null drawn from {verdict['permutations']} shuffles of the group "
        f"labels. Judged by \\texttt{{{esc(data['judge'].split(':')[-1])}}} at "
        f"{data['samples']} samples per cell.",
        "tab:suppadt", "llrrr",
        ["composition", "axis", "excess", "$t$", "$p_{\\mathrm{adj}}$"], rows,
        wide=False)
    write("supp_adt.tex", lines)


def calibration() -> None:
    """What the statistic does when there is nothing to find, and when there is."""
    data = load("calibration", "summary.json")
    false_positives = data["false_positives"]
    rows = [[f"{point['shift']:.2f}", f"{point['rejects']:.3f}",
             f"{point['names_the_cell']:.3f}"] for point in data["power"]]
    lines = table(
        "What the test does when an effect is planted. \\emph{Shift} is how "
        "far one cell was moved, \\emph{rejects} is how often the test called "
        "it, and \\emph{names it} is how often the cell it named was the one "
        "that moved. A test that rejects without naming the right cell has "
        "found something real in the wrong place, which is why the paper "
        "reports the null rather than its strongest cell. Measured over "
        f"{data['power_trials']} trials at {data['permutations']} permutations "
        "each.",
        "tab:supppower", "ccc", ["shift", "rejects", "names it"], rows)
    lines += [r"", *table(
        "What the test does when nothing was planted. Each rate is over "
        f"{false_positives['with_control']['trials']} trials on data with no "
        "effect in it. Dropping the control raises the rate above the nominal "
        "level, which is why every study here carries one.",
        "tab:suppfpr", "lcc", ["", "trials", "false positive rate"],
        [["with a control",
          f"{false_positives['with_control']['trials']}",
          f"{false_positives['with_control']['rate']:.3f}"],
         ["without a control",
          f"{false_positives['no_control']['trials']}",
          f"{false_positives['no_control']['rate']:.3f}"]])]
    write("supp_calibration.tex", lines)


def main() -> None:
    argparse.ArgumentParser(description=__doc__).parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    models()
    scenario_listing()
    probe_listing()
    crossing()
    subject_side()
    substitution()
    architecture()
    calibration()


if __name__ == "__main__":
    main()
