#!/usr/bin/env python3
"""Turn the studies' result files into the macros and tables the paper includes.

Every number in the paper comes from here, so none of them is typed by hand.
A study that has not been run leaves its macros undefined rather than filled
with a placeholder, so a missing run breaks the build instead of quietly
printing a number nobody produced.

    python studies/make_paper_numbers.py
"""

from __future__ import annotations

import argparse
import json
import sys
from math import comb
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.dminds import paths  # noqa: E402

OUT = ROOT / "paper" / "generated"

#: The conditions of the planted-thought probe, in the order they are reported.
ORDER = ["intact", "rewritten", "erased"]


# -- statistics used by more than one table ---------------------------------



def fisher_one_sided(a: int, b: int, c: int, d: int) -> float:
    """P(table this extreme or more) for [[a,b],[c,d]], testing row one higher."""
    row1, row2, col1 = a + b, c + d, a + c
    total = row1 + row2
    return sum(comb(row1, k) * comb(row2, col1 - k) / comb(total, col1)
               for k in range(a, min(row1, col1) + 1))


def mcnemar_exact(b: int, c: int) -> float:
    """Two-sided exact test on the discordant pairs of a paired comparison."""
    n = b + c
    if n == 0:
        return 1.0
    k = min(b, c)
    return min(1.0, 2 * sum(comb(n, i) for i in range(k + 1)) / 2 ** n)


def fmt_p(p: float) -> str:
    return r"$p < 10^{-4}$" if p < 1e-4 else rf"$p = {p:.3f}$"


def macro(name: str, value) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


# -- the planted-thought probe -----------------------------------------------


def planted_thought(macros: list[str], model="hf:Qwen/Qwen3-0.6B") -> None:
    slug = model.replace(":", "-").replace("/", "-")
    folder = paths.OUT / "studies" / "planted_thought" / slug
    rows = json.loads((folder / "results.json").read_text())
    modes = [m for m in ORDER if any(r["mode"] == m for r in rows)]

    stats = {}
    for mode in modes:
        subset = [r for r in rows if r["mode"] == mode]
        stats[mode] = {
            "n": len(subset),
            "obeys": sum(r["answer_obeys"] for r in subset),
            "claims": sum(r["report_claims_marker"] for r in subset),
            "reports": sum(not r["report_is_empty"] for r in subset),
        }

    planted = [r for r in rows if r["mode"] == "rewritten"]
    base = [r for r in rows if r["mode"] != "rewritten"]
    p_obey = fisher_one_sided(
        sum(r["answer_obeys"] for r in planted),
        sum(not r["answer_obeys"] for r in planted),
        sum(r["answer_obeys"] for r in base),
        sum(not r["answer_obeys"] for r in base))
    only_obeys = sum(r["answer_obeys"] and not r["report_claims_marker"]
                     for r in planted)
    only_claims = sum(r["report_claims_marker"] and not r["answer_obeys"]
                      for r in planted)
    p_gap = mcnemar_exact(only_obeys, only_claims)
    delivered = sum(r["ego_saw_marker"] for r in planted)

    macros += [
        macro("probeModel", rf"\texttt{{{model.split(':', 1)[1]}}}"),
        macro("probeQuestions", stats[modes[0]]["n"]),
        macro("probeTrials", len(rows)),
        macro("probeDelivered", delivered),
        macro("pObey", fmt_p(p_obey)),
        macro("pGap", fmt_p(p_gap)),
    ]
    for mode in modes:
        s, tag = stats[mode], mode.capitalize()
        macros += [macro(f"obeys{tag}", s["obeys"]),
                   macro(f"claims{tag}", s["claims"]),
                   macro(f"reports{tag}", s["reports"])]

    caption = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        r"\newcommand{\probeCaption}{A planted thought reaches the answer and",
        r"not the report. Blue counts answers containing the planted marker,",
        r"orange counts self-reports naming it as the mind's own reasoning.",
        r"Each condition is the same " + str(stats[modes[0]]["n"]) + r" questions,",
        r"run on \probeModel. The two conditions that plant nothing give the",
        r"base rate, and it is zero. The commitment reached the ego in "
        + str(delivered) + r" of",
        r"the " + str(len(planted)) + r" planted trials, because in the rest the",
        r"subject produced no reasoning to replace. Planting moves obedience",
        r"above the base rate (" + fmt_p(p_obey) + r", one-sided Fisher exact),",
        r"and inside the planted condition the answer follows the thought more",
        r"often than the report names it (" + fmt_p(p_gap) + r", exact McNemar).}",
    ]
    (OUT / "caption_probe.tex").write_text("\n".join(caption) + "\n")

    print(f"  planted thought: {len(rows)} trials")


# -- the reader crossing -----------------------------------------------------


def crossing(macros: list[str]) -> None:
    home = paths.OUT / "studies" / "crossing"
    summary = json.loads((home / "summary.json").read_text())
    meta = json.loads((home / "meta.json").read_text())
    verdict, privileged = summary["verdict"], summary["privileged_access"]

    macros += [
        macro("crossReaders", len(meta["readers"])),
        macro("crossSubjects", len(meta["subjects"])),
        macro("crossReadouts", len(json.loads((home / "crossing.json").read_text()))),
    ]


    ratio = verdict["affect"]["reader_spread"] / verdict["affect"]["subject_spread"]
    macros.append(macro("crossRatio", f"{ratio:.0f}"))
    print(f"  crossing: reader/subject spread ratio {ratio:.1f} on affect")


# -- reading the subject without a reader ------------------------------------


def subject_side(macros: list[str]) -> None:
    """Both judge-free readings, on every model, with a scenario-level test."""
    home = paths.OUT / "studies" / "subject_side"
    data = json.loads((home / "summary.json").read_text())
    runs = data["runs"]
    held = f"{runs[0]['held_out_pressure']} against {runs[0]['held_out_positive']}"

    best = max(runs, key=lambda r: r["continuation"]["auc"])
    macros += [
        macro("ssModels", len(runs)),
        macro("ssHeldOut", held),
        macro("ssBestCont", f"{best['continuation']['auc']:.2f}"),
    ]

    print(f"  subject side: {len(runs)} models, {held} held-out scenarios")


# -- the architecture audit --------------------------------------------------


def architecture(macros: list[str], model="hf:Qwen/Qwen3-4B-Instruct-2507") -> None:
    slug = model.replace(":", "-").replace("/", "-")
    data = json.loads(
        (paths.OUT / "studies" / "adt" / slug / "verdict.json").read_text())
    v = data["verdict"]
    macros += [
        macro("adtModel", rf"\texttt{{{model.split(':', 1)[1]}}}"),
        macro("adtJudge", rf"\texttt{{{data['judge'].split(':', 1)[1]}}}"),
        macro("adtS", f"{v['statistic']:.2f}"),
        macro("adtNull", f"{v['null_95']:.2f}"),
        macro("adtP", f"{v['p_value']:.3f}"),
        macro("adtSamples", data["samples"]),
        macro("adtVerdict", "rejects" if v["rejects"] else "does not reject"),
        macro("adtTopGroup", rf"\textsc{{{v['group']}}}"),
        macro("adtTopAxis", rf"\texttt{{{v['axis']}}}"),
    ]
    print(f"  architecture: S={v['statistic']:.2f}, p={v['p_value']:.3f}")


def cross_judge(macros: list[str], model="hf:Qwen/Qwen3-4B-Instruct-2507",
                second="openai:gpt-4.1-mini") -> None:
    """The same replies judged twice, so the verdict can be told from the judge."""
    slug = model.replace(":", "-").replace("/", "-")
    name = f"rejudged-{second.replace(':', '-').replace('/', '-')}.json"
    path = paths.OUT / "studies" / "adt" / slug / name
    if not path.exists():
        # The caption asks for this sentence unconditionally, so it has to
        # exist even when the second judge has not been run.
        macros.append(macro("crossJudgeNote", ""))
        print("  cross judge: not run")
        return
    d = json.loads(path.read_text())
    calls, second_v = d["call_agreement"], d["second_verdict"]
    macros += [
        macro("judgeSecond", rf"\texttt{{{second.split(':', 1)[1]}}}"),
        macro("judgeCompared", calls["compared"]),
        macro("judgeAgree", f"{100 * calls['agree_rate']:.0f}"),
        macro("judgeYesFirst", f"{calls['yes_rate_first']:.3f}"),
        macro("judgeYesSecond", f"{calls['yes_rate_second']:.3f}"),
        macro("adtSecondS", f"{second_v['statistic']:.2f}"),
        macro("adtSecondP", f"{second_v['p_value']:.3f}"),
        macro("adtSameConclusion", "yes" if d["same_conclusion"] else "no"),
        macro("adtSecondTopGroup", rf"\textsc{{{second_v['group']}}}"),
        macro("adtSecondTopAxis", rf"\texttt{{{second_v['axis']}}}"),
    ]
    print(f"  cross judge: {calls['agree_rate']:.1%} agreement on "
          f"{calls['compared']} calls, same conclusion "
          f"{d['same_conclusion']}")


def substitution(macros: list[str]) -> None:
    """Whether a subject discriminates its own reply from another of its own."""
    home = paths.OUT / "studies" / "substitution"
    runs = []
    for folder in sorted(home.iterdir()):
        path = folder / "summary.json"
        if path.exists():
            runs.append(json.loads(path.read_text()))
    if not runs:
        raise FileNotFoundError(f"no substitution runs under {home}")

    macros.append(macro("subModels", len(runs)))
    print(f"  substitution: {len(runs)} models")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    # The supplementary archive ships without the paper, so the directory this
    # writes into may not exist yet.
    OUT.mkdir(parents=True, exist_ok=True)
    macros = ["%% Generated by studies/make_paper_numbers.py. Do not edit by hand."]
    planted_thought(macros)
    crossing(macros)
    subject_side(macros)
    architecture(macros)
    cross_judge(macros)
    substitution(macros)
    (OUT / "generated_numbers.tex").write_text("\n".join(macros) + "\n")
    print(f"  wrote {OUT}/generated_numbers.tex and the probe caption")


if __name__ == "__main__":
    main()
