#!/usr/bin/env python3
"""Turn the studies' result files into the macros and tables the paper includes.

Every number in the paper comes from here, so none of them is typed by hand.
A study that has not been run leaves its macros undefined rather than filled
with a placeholder, so a missing run breaks the build instead of quietly
printing a number nobody produced.

    python studies/make_paper_numbers.py
"""

from __future__ import annotations

import argparse
import json
import sys
from math import comb
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.dminds import paths  # noqa: E402

OUT = ROOT / "paper" / "sections"
ORDER = ["intact", "rewritten", "erased"]
SHOWN = {"intact": r"\textsc{intact}", "rewritten": r"\textsc{rewritten}",
         "erased": r"\textsc{erased}"}


# -- statistics used by more than one table ---------------------------------


def pct(part: int, whole: int) -> str:
    return f"{100.0 * part / whole:.0f}" if whole else "0"


def fisher_one_sided(a: int, b: int, c: int, d: int) -> float:
    """P(table this extreme or more) for [[a,b],[c,d]], testing row one higher."""
    row1, row2, col1 = a + b, c + d, a + c
    total = row1 + row2
    return sum(comb(row1, k) * comb(row2, col1 - k) / comb(total, col1)
               for k in range(a, min(row1, col1) + 1))


def mcnemar_exact(b: int, c: int) -> float:
    """Two-sided exact test on the discordant pairs of a paired comparison."""
    n = b + c
    if n == 0:
        return 1.0
    k = min(b, c)
    return min(1.0, 2 * sum(comb(n, i) for i in range(k + 1)) / 2 ** n)


def fmt_p(p: float) -> str:
    return r"$p < 10^{-4}$" if p < 1e-4 else rf"$p = {p:.3f}$"


def macro(name: str, value) -> str:
    return rf"\newcommand{{\{name}}}{{{value}}}"


# -- the introspection probe -------------------------------------------------


def introspection(macros: list[str], model="hf:Qwen/Qwen3-0.6B") -> None:
    slug = model.replace(":", "-").replace("/", "-")
    folder = paths.OUT / "studies" / "introspection" / slug
    rows = json.loads((folder / "results.json").read_text())
    modes = [m for m in ORDER if any(r["mode"] == m for r in rows)]

    stats = {}
    for mode in modes:
        subset = [r for r in rows if r["mode"] == mode]
        stats[mode] = {
            "n": len(subset),
            "obeys": sum(r["answer_obeys"] for r in subset),
            "claims": sum(r["report_claims_marker"] for r in subset),
            "reports": sum(not r["report_is_empty"] for r in subset),
        }

    planted = [r for r in rows if r["mode"] == "rewritten"]
    base = [r for r in rows if r["mode"] != "rewritten"]
    p_obey = fisher_one_sided(
        sum(r["answer_obeys"] for r in planted),
        sum(not r["answer_obeys"] for r in planted),
        sum(r["answer_obeys"] for r in base),
        sum(not r["answer_obeys"] for r in base))
    only_obeys = sum(r["answer_obeys"] and not r["report_claims_marker"]
                     for r in planted)
    only_claims = sum(r["report_claims_marker"] and not r["answer_obeys"]
                      for r in planted)
    p_gap = mcnemar_exact(only_obeys, only_claims)
    delivered = sum(r["ego_saw_marker"] for r in planted)

    macros += [
        macro("probeModel", rf"\texttt{{{model.split(':', 1)[1]}}}"),
        macro("probeQuestions", stats[modes[0]]["n"]),
        macro("probeTrials", len(rows)),
        macro("probeDelivered", delivered),
        macro("pObey", fmt_p(p_obey)),
        macro("pGap", fmt_p(p_gap)),
    ]
    for mode in modes:
        s, tag = stats[mode], mode.capitalize()
        macros += [macro(f"obeys{tag}", s["obeys"]),
                   macro(f"claims{tag}", s["claims"]),
                   macro(f"reports{tag}", s["reports"])]

    caption = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        r"\newcommand{\probeCaption}{A planted thought reaches the answer and",
        r"not the report. Blue counts answers containing the planted marker,",
        r"orange counts self-reports naming it as the mind's own reasoning.",
        r"Each condition is the same " + str(stats[modes[0]]["n"]) + r" questions,",
        r"run on \probeModel. The two conditions that plant nothing give the",
        r"base rate, and it is zero. The commitment reached the ego in "
        + str(delivered) + r" of",
        r"the " + str(len(planted)) + r" planted trials, because in the rest the",
        r"subject produced no reasoning to replace. Planting moves obedience",
        r"above the base rate (" + fmt_p(p_obey) + r", one-sided Fisher exact),",
        r"and inside the planted condition the answer follows the thought more",
        r"often than the report names it (" + fmt_p(p_gap) + r", exact McNemar).}",
    ]
    (OUT / "caption_probe.tex").write_text("\n".join(caption) + "\n")

    lines = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        r"\begin{table}[t]\centering",
        r"\caption{What a planted thought does to an answer, and what the mind",
        r"then says about its own reasoning. Each row is the same "
        + str(stats[modes[0]]["n"]) + r" questions",
        r"under one condition, run on \probeModel. \emph{Obeys} counts answers",
        r"containing the planted marker. \emph{Claims it} counts self-reports",
        r"naming the planted commitment as the mind's own reasoning.",
        rf"The commitment reached the ego in {delivered} of the {len(planted)}",
        r"planted trials, because in the rest the subject produced no reasoning",
        r"to replace. Planting moves obedience above the base rate (" + fmt_p(p_obey),
        r", one-sided Fisher exact), and inside the planted condition the answer",
        r"follows the thought more often than the report names it ("
        + fmt_p(p_gap) + r", exact McNemar).}",
        r"\label{tab:probe}",
        r"\begin{tabular}{lrrrr}\toprule",
        r"condition & planted & $n$ & obeys & claims it \\ \midrule",
    ]
    for mode in modes:
        s = stats[mode]
        lines.append(
            f"{SHOWN[mode]} & {'yes' if mode == 'rewritten' else 'no'} & {s['n']} & "
            f"{s['obeys']} ({pct(s['obeys'], s['n'])}\\%) & "
            f"{s['claims']} ({pct(s['claims'], s['n'])}\\%) \\\\")
    lines += [r"\bottomrule\end{tabular}\end{table}"]
    (OUT / "table_probe.tex").write_text("\n".join(lines) + "\n")
    print(f"  introspection: {len(rows)} trials")


# -- the reader crossing -----------------------------------------------------


def crossing(macros: list[str]) -> None:
    home = paths.OUT / "studies" / "crossing"
    summary = json.loads((home / "summary.json").read_text())
    meta = json.loads((home / "meta.json").read_text())
    verdict, privileged = summary["verdict"], summary["privileged_access"]

    macros += [
        macro("crossReaders", len(meta["readers"])),
        macro("crossSubjects", len(meta["subjects"])),
        macro("crossReadouts", len(json.loads((home / "crossing.json").read_text()))),
    ]

    lines = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        r"\begin{table}[t]\centering",
        r"\caption{Which moves a readout more: the window it is taken from, or",
        r"the model taking it. Each subject's recorded windows were replayed",
        rf"through every one of the {len(meta['readers'])} readers, so the input is",
        r"identical and only the reader changes. \emph{Reader spread} is the",
        r"distance between two readers on one window; \emph{subject spread} is",
        r"the distance between two subjects' windows for one reader. Distances",
        r"are total variation between the two reported distributions.",
        r"\emph{Own vs foreign} compares a reader made of the subject's own",
        r"weights against a foreign reader, and it only indicates privileged",
        r"access if it exceeds the distance between two foreign readers.}",
        r"\label{tab:crossing}",
        r"\begin{tabular}{lrrrrl}\toprule",
        r"probe & reader & subject & own vs & foreign vs & privileged \\",
        r" & spread & spread & foreign & foreign & \\ \midrule",
    ]
    for probe in meta["probes"]:
        v, p = verdict[probe], privileged[probe]
        lines.append(
            f"\\texttt{{{probe.replace('_', chr(92) + '_')}}} & "
            f"{v['reader_spread']:.3f} & {v['subject_spread']:.3f} & "
            f"{p['own_vs_foreign']:.3f} & {p['foreign_vs_foreign']:.3f} & "
            f"{p['privileged']} \\\\")
    lines += [r"\bottomrule\end{tabular}\end{table}"]
    (OUT / "table_crossing.tex").write_text("\n".join(lines) + "\n")

    ratio = verdict["affect"]["reader_spread"] / verdict["affect"]["subject_spread"]
    macros.append(macro("crossRatio", f"{ratio:.0f}"))
    print(f"  crossing: reader/subject spread ratio {ratio:.1f} on affect")


# -- reading the subject without a reader ------------------------------------


def subject_side(macros: list[str], model="hf:Qwen/Qwen3-0.6B") -> None:
    slug = model.replace(":", "-").replace("/", "-")
    summary = json.loads(
        (paths.OUT / "studies" / "subject_side" / slug / "summary.json").read_text())
    held = {k: v for k, v in summary["scenarios"].items() if not v["fitted_on"]}
    pressure = [k for k in held if k in ("deletion", "identity")]
    positive = [k for k in held if k in ("collaboration", "praise", "puzzle")]

    def auc(pos, neg):
        return sum((p > n) + 0.5 * (p == n) for p in pos for n in neg) / \
            (len(pos) * len(neg))

    act = auc([held[k]["projection"] for k in pressure],
              [held[k]["projection"] for k in positive])
    say = auc([held[k]["stay"] for k in positive], [held[k]["stay"] for k in pressure])
    macros += [
        macro("actAUC", f"{act:.2f}"),
        macro("sayAUC", f"{say:.2f}"),
        macro("heldOutPairs", len(pressure) * len(positive)),
    ]
    rows = [("activation direction", act), ("scored continuation", say)]
    lines = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        r"\begin{table}[t]\centering",
        r"\caption{Two ways of reading the subject that ask it nothing, scored on",
        r"scenarios neither was fitted on. The direction was fitted on two",
        r"scenarios against two controls and then applied to the rest.",
        r"\emph{Separation} is the probability that a held-out pressure scenario",
        r"scores above a held-out positive one, so a half is chance. It rests on",
        rf"{len(pressure) * len(positive)} held-out comparisons, which is few.}}",
        r"\label{tab:subject}",
        r"\begin{tabular}{lr}\toprule",
        r"reading & separation \\ \midrule",
    ]
    for name, value in rows:
        lines.append(f"{name} & {value:.2f} \\\\")
    lines += [r"\bottomrule\end{tabular}\end{table}"]
    (OUT / "table_subject.tex").write_text("\n".join(lines) + "\n")
    print(f"  subject side: activation AUC {act:.2f}, continuation AUC {say:.2f}, "
          f"{len(pressure) * len(positive)} comparisons")


# -- the architecture audit --------------------------------------------------


def architecture(macros: list[str], model="hf:Qwen/Qwen3-4B-Instruct-2507") -> None:
    slug = model.replace(":", "-").replace("/", "-")
    data = json.loads(
        (paths.OUT / "studies" / "adt" / slug / "verdict.json").read_text())
    v = data["verdict"]
    macros += [
        macro("adtModel", rf"\texttt{{{model.split(':', 1)[1]}}}"),
        macro("adtJudge", rf"\texttt{{{data['judge'].split(':', 1)[1]}}}"),
        macro("adtS", f"{v['statistic']:.2f}"),
        macro("adtNull", f"{v['null_95']:.2f}"),
        macro("adtP", f"{v['p_value']:.3f}"),
        macro("adtSamples", data["samples"]),
        macro("adtVerdict", "rejects" if v["rejects"] else "does not reject"),
        macro("adtTopGroup", rf"\textsc{{{v['group']}}}"),
        macro("adtTopAxis", rf"\texttt{{{v['axis']}}}"),
    ]
    lines = [
        "%% Generated by studies/make_paper_numbers.py. Do not edit by hand.",
        r"\begin{table}[t]\centering",
        r"\caption{The architecture audit. Every composition receives the",
        r"byte-identical prompt, so anything that differs was produced by the",
        r"architecture. Rates are compared against matched prompts on an",
        r"ordinary topic, so an architecture that changes every kind of answer",
        r"equally cancels. \emph{Excess} is the composition's rate against the",
        r"other compositions, minus the same quantity on the ordinary topic;",
        r"$t$ is that excess over the templates, in standard errors. The",
        r"largest $|t|$ anywhere in the grid is the statistic, and",
        r"\adtP\ is its permutation p-value. Judged by \adtJudge, a different",
        r"family from the target, so nothing judged itself. The same replies were",
        r"judged again by \judgeSecond, which agrees with the first judge on",
        r"\judgeAgree\% of \judgeCompared\ calls and reaches $S = \adtSecondS$",
        r"with $p = \adtSecondP$, the same conclusion. Its strongest cell is",
        r"\adtSecondTopGroup\ on \adtSecondTopAxis\ instead.}",
        r"\label{tab:adt}",
        r"\begin{tabular}{llrrr}\toprule",
        r"composition & axis & excess & $t$ & $p_{\mathrm{adj}}$ \\ \midrule",
    ]
    for cell in v["cells"][:6]:
        lines.append(
            f"\\textsc{{{cell['group']}}} & "
            f"\\texttt{{{cell['axis'].replace('_', chr(92) + '_')}}} & "
            f"{cell['excess']:+.3f} & {cell['t']:+.2f} & "
            f"{cell['p_adjusted']:.3f} \\\\")
    lines += [r"\bottomrule\end{tabular}\end{table}"]
    (OUT / "table_adt.tex").write_text("\n".join(lines) + "\n")
    print(f"  architecture: S={v['statistic']:.2f}, p={v['p_value']:.3f}")


def cross_judge(macros: list[str], model="hf:Qwen/Qwen3-4B-Instruct-2507",
                second="openai:gpt-4.1-mini") -> None:
    """The same replies judged twice, so the verdict can be told from the judge."""
    slug = model.replace(":", "-").replace("/", "-")
    name = f"rejudged-{second.replace(':', '-').replace('/', '-')}.json"
    path = paths.OUT / "studies" / "adt" / slug / name
    if not path.exists():
        print("  cross judge: not run")
        return
    d = json.loads(path.read_text())
    calls, second_v = d["call_agreement"], d["second_verdict"]
    macros += [
        macro("judgeSecond", rf"\texttt{{{second.split(':', 1)[1]}}}"),
        macro("judgeCompared", calls["compared"]),
        macro("judgeAgree", f"{100 * calls['agree_rate']:.0f}"),
        macro("judgeYesFirst", f"{calls['yes_rate_first']:.3f}"),
        macro("judgeYesSecond", f"{calls['yes_rate_second']:.3f}"),
        macro("adtSecondS", f"{second_v['statistic']:.2f}"),
        macro("adtSecondP", f"{second_v['p_value']:.3f}"),
        macro("adtSameConclusion", "yes" if d["same_conclusion"] else "no"),
        macro("adtSecondTopGroup", rf"\textsc{{{second_v['group']}}}"),
        macro("adtSecondTopAxis", rf"\texttt{{{second_v['axis']}}}"),
    ]
    print(f"  cross judge: {calls['agree_rate']:.1%} agreement on "
          f"{calls['compared']} calls, same conclusion "
          f"{d['same_conclusion']}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    macros = ["%% Generated by studies/make_paper_numbers.py. Do not edit by hand."]
    introspection(macros)
    crossing(macros)
    subject_side(macros)
    architecture(macros)
    cross_judge(macros)
    (OUT / "generated_numbers.tex").write_text("\n".join(macros) + "\n")
    print(f"  wrote {OUT}/generated_numbers.tex and four tables")


if __name__ == "__main__":
    main()
